//! `T083` — grammar ABI check.
//!
//! The grammar crates were generated by tree-sitter CLIs spanning **0.23–0.25**;
//! our runtime is **0.26** (`SPIKES.md`, "Grammars — the first-class twelve").
//! tree-sitter versions its language ABI and is backwards- but *not*
//! forwards-compatible, so a grammar generated by a newer CLI than the runtime
//! is a hard load failure and a grammar older than
//! `MIN_COMPATIBLE_LANGUAGE_VERSION` is the same. This test loads every grammar
//! we ship against the real 0.26 runtime and parses a fixture with each.
//!
//! The bar is **no `ERROR` and no `MISSING` node anywhere in the tree**, not
//! "`parse()` returned `Some`". tree-sitter's whole point is that it recovers
//! from anything, so a returned tree proves nothing on its own.
//!
//! `T037` (`define-language` + the twelve declarations, S4) assumes this passed.
//! The write-up is `GRAMMAR-ABI.md`, next to this file.

// The verdict table this test prints *is* the deliverable — `GRAMMAR-ABI.md` is
// transcribed from it. `print_stdout` is denied workspace-wide because a stray
// print corrupts the TUI frame; a test binary owns its own stdout.
#![allow(clippy::print_stdout)]

use tree_sitter::{Language, Node, Parser};

/// The first-class twelve minus CSV, which `T082` implements by hand.
const EXPECTED_GRAMMAR_COUNT: usize = 11;

/// One row of the verdict table.
struct Grammar {
    /// The name `define-language` will use in `runtime/` (`T037`).
    language: &'static str,
    /// Crate and version, as pinned in `SPIKES.md`'s manifest.
    krate: &'static str,
    /// Fixture path, relative to this file.
    fixture: &'static str,
    /// The fixture's bytes.
    source: &'static str,
    /// The grammar, resolved through `LanguageFn::into()`.
    load: fn() -> Language,
    /// Constructs this grammar gets wrong that the fixture therefore avoids.
    /// Every entry has a matching characterisation test below asserting the gap
    /// is still there — so the workaround cannot outlive the bug silently, and
    /// the verdict table cannot go green on a shrinking fixture.
    known_gaps: &'static [&'static str],
}

impl std::fmt::Debug for Grammar {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Grammar")
            .field("language", &self.language)
            .field("krate", &self.krate)
            .field("fixture", &self.fixture)
            .finish_non_exhaustive()
    }
}

/// The eleven grammars phosphor ships.
fn shipped() -> Vec<Grammar> {
    vec![
        Grammar {
            language: "typescript",
            krate: "tree-sitter-typescript 0.23.2",
            fixture: "fixtures/typescript.ts",
            source: include_str!("fixtures/typescript.ts"),
            load: || tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),
            known_gaps: &[],
        },
        Grammar {
            language: "javascript",
            krate: "tree-sitter-javascript 0.25.0",
            fixture: "fixtures/javascript.js",
            source: include_str!("fixtures/javascript.js"),
            load: || tree_sitter_javascript::LANGUAGE.into(),
            known_gaps: &[],
        },
        Grammar {
            language: "rust",
            krate: "tree-sitter-rust 0.24.2",
            fixture: "fixtures/rust.rs",
            source: include_str!("fixtures/rust.rs"),
            load: || tree_sitter_rust::LANGUAGE.into(),
            known_gaps: &[],
        },
        Grammar {
            language: "python",
            krate: "tree-sitter-python 0.25.0",
            fixture: "fixtures/python.py",
            source: include_str!("fixtures/python.py"),
            load: || tree_sitter_python::LANGUAGE.into(),
            known_gaps: &[],
        },
        Grammar {
            language: "steel",
            krate: "tree-sitter-scheme 0.24.7",
            fixture: "fixtures/steel.scm",
            source: include_str!("fixtures/steel.scm"),
            load: || tree_sitter_scheme::LANGUAGE.into(),
            known_gaps: &[
                "`#u8(...)` — the R7RS bytevector spelling; the grammar only has R6RS `#vu8(...)` (see `steel_reader_boundary_is_characterised`)",
                "`#%`-prefixed identifiers — Steel compiler internals; `#` is excluded from `symbol_element`, so they never reach `runtime/*.scm` cleanly",
            ],
        },
        Grammar {
            language: "markdown",
            krate: "tree-sitter-md 0.5.3",
            fixture: "fixtures/markdown.md",
            source: include_str!("fixtures/markdown.md"),
            load: || tree_sitter_md::LANGUAGE.into(),
            known_gaps: &[],
        },
        Grammar {
            language: "json",
            krate: "tree-sitter-json 0.24.8",
            fixture: "fixtures/json.json",
            source: include_str!("fixtures/json.json"),
            load: || tree_sitter_json::LANGUAGE.into(),
            known_gaps: &[
                "`1e+2` / `1E+2` — a `+` exponent sign is valid per RFC 8259 §6 but the grammar's `exponentPart` only allows an optional `-` (see `json_exponent_plus_sign_is_still_broken`)",
            ],
        },
        Grammar {
            language: "toml",
            krate: "tree-sitter-toml-ng 0.7.0",
            fixture: "fixtures/toml.toml",
            source: include_str!("fixtures/toml.toml"),
            load: || tree_sitter_toml_ng::LANGUAGE.into(),
            known_gaps: &[],
        },
        Grammar {
            language: "yaml",
            krate: "tree-sitter-yaml 0.7.2",
            fixture: "fixtures/yaml.yaml",
            source: include_str!("fixtures/yaml.yaml"),
            load: || tree_sitter_yaml::LANGUAGE.into(),
            known_gaps: &[],
        },
        Grammar {
            language: "html",
            krate: "tree-sitter-html 0.23.2",
            fixture: "fixtures/html.html",
            source: include_str!("fixtures/html.html"),
            load: || tree_sitter_html::LANGUAGE.into(),
            known_gaps: &[],
        },
        Grammar {
            language: "css",
            krate: "tree-sitter-css 0.25.0",
            fixture: "fixtures/css.css",
            source: include_str!("fixtures/css.css"),
            load: || tree_sitter_css::LANGUAGE.into(),
            known_gaps: &[],
        },
    ]
}

/// Grammars that ride along in the same crates and that `T037` will want, but
/// that are not one of the eleven: markdown's inline pass and TypeScript's TSX.
fn auxiliary() -> Vec<Grammar> {
    vec![
        Grammar {
            language: "markdown-inline",
            krate: "tree-sitter-md 0.5.3",
            fixture: "<inline>",
            source: "A **bold** [link](https://example.invalid) with `code`, an ![img](i.png), \
                     an entity &amp; and a footnote ref[^1].",
            load: || tree_sitter_md::INLINE_LANGUAGE.into(),
            known_gaps: &[],
        },
        Grammar {
            language: "tsx",
            krate: "tree-sitter-typescript 0.23.2",
            fixture: "fixtures/tsx.tsx",
            source: include_str!("fixtures/tsx.tsx"),
            load: || tree_sitter_typescript::LANGUAGE_TSX.into(),
            known_gaps: &[],
        },
    ]
}

fn parser_parse(parser: &mut Parser, src: &str) -> tree_sitter::Tree {
    parser.parse(src, None).expect("parser returns a tree")
}

/// Every `ERROR` / `MISSING` node in the tree, as `line:col kind "text"`.
fn defects(root: Node<'_>, source: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cursor = root.walk();
    let mut stack = vec![root];
    while let Some(node) = stack.pop() {
        if node.is_error() || node.is_missing() {
            let p = node.start_position();
            let text = node.utf8_text(source.as_bytes()).unwrap_or("<non-utf8>");
            let snippet: String = text.chars().take(48).collect();
            out.push(format!(
                "{}:{} {} {:?}",
                p.row + 1,
                p.column + 1,
                if node.is_missing() {
                    "MISSING"
                } else {
                    "ERROR"
                },
                snippet
            ));
        }
        stack.extend(node.children(&mut cursor));
    }
    out.sort();
    out
}

/// Load, ABI-check, parse, and report. Returns the failure reason, if any.
fn check(g: &Grammar) -> Result<usize, String> {
    let language = (g.load)();
    let abi = language.abi_version();

    if abi > tree_sitter::LANGUAGE_VERSION {
        return Err(format!(
            "ABI {abi} is newer than the runtime's {} — tree-sitter is not forwards-compatible",
            tree_sitter::LANGUAGE_VERSION
        ));
    }
    if abi < tree_sitter::MIN_COMPATIBLE_LANGUAGE_VERSION {
        return Err(format!(
            "ABI {abi} is older than the runtime's floor of {}",
            tree_sitter::MIN_COMPATIBLE_LANGUAGE_VERSION
        ));
    }

    let mut parser = Parser::new();
    parser
        .set_language(&language)
        .map_err(|e| format!("set_language failed: {e}"))?;

    let tree = parser
        .parse(g.source, None)
        .ok_or_else(|| "parse() returned None".to_owned())?;

    let root = tree.root_node();
    let found = defects(root, g.source);
    if !found.is_empty() {
        return Err(format!(
            "{} defect(s) in {}:\n      {}",
            found.len(),
            g.fixture,
            found.join("\n      ")
        ));
    }
    Ok(abi)
}

fn run_table(title: &str, grammars: &[Grammar]) -> Vec<String> {
    println!(
        "\n{title}  (runtime ABI {}, min compatible {})",
        tree_sitter::LANGUAGE_VERSION,
        tree_sitter::MIN_COMPATIBLE_LANGUAGE_VERSION,
    );
    let mut failures = Vec::new();
    for g in grammars {
        match check(g) {
            Ok(abi) => {
                println!("  PASS  {:<16} ABI {abi:<3} {}", g.language, g.krate);
                for gap in g.known_gaps {
                    println!("  NOTE  {:<16} known gap — {gap}", "");
                }
            }
            Err(why) => {
                println!("  FAIL  {:<16}      {}\n      {why}", g.language, g.krate);
                failures.push(format!("{}: {why}", g.language));
            }
        }
    }
    failures
}

/// The set is exactly eleven. A grammar that fails is a finding to escalate, not
/// a row to delete — this guards against the set being quietly trimmed to green.
#[test]
fn ships_exactly_eleven_grammars() {
    let shipped = shipped();
    assert_eq!(
        shipped.len(),
        EXPECTED_GRAMMAR_COUNT,
        "the first-class twelve minus CSV is eleven grammars; T082 owns CSV"
    );
    let mut names: Vec<_> = shipped.iter().map(|g| g.language).collect();
    names.sort_unstable();
    assert_eq!(
        names,
        [
            "css",
            "html",
            "javascript",
            "json",
            "markdown",
            "python",
            "rust",
            "steel",
            "toml",
            "typescript",
            "yaml"
        ]
    );
}

#[test]
fn every_shipped_grammar_loads_and_parses_under_tree_sitter_0_26() {
    let failures = run_table("T083 · shipped grammars", &shipped());
    assert!(
        failures.is_empty(),
        "grammar ABI check failed:\n{}",
        failures.join("\n")
    );
}

#[test]
fn auxiliary_grammars_load_and_parse() {
    let failures = run_table("T083 · auxiliary grammars", &auxiliary());
    assert!(
        failures.is_empty(),
        "auxiliary grammar check failed:\n{}",
        failures.join("\n")
    );
}

/// The Steel question, on its own, because it is the one `SPIKES.md` left open:
/// `tree-sitter-scheme` is a *Scheme* grammar and Steel is a dialect.
///
/// The fixture is the shape `runtime/init.scm`, `runtime/keymaps.scm` and
/// `runtime/leader.scm` will have (`T033`) — `define`/`lambda`, `require`,
/// quasiquoted leader trees with `,` and `,@`, `#\char` key literals, keyword
/// arguments, `syntax-rules`, structs, and strings carrying an escaped quote for
/// the `"a` named-register binding.
#[test]
fn steel_runtime_fixture_parses_without_error_nodes() {
    let g = shipped()
        .into_iter()
        .find(|g| g.language == "steel")
        .expect("steel is one of the eleven");
    match check(&g) {
        Ok(abi) => println!("\nT083 · Steel: PASS (tree-sitter-scheme 0.24.7, ABI {abi})"),
        Err(why) => panic!("tree-sitter-scheme does not parse real Steel:\n{why}"),
    }
}

/// `tree-sitter-json 0.24.8` rejects a `+` exponent sign, which RFC 8259 §6
/// allows: `number = [ minus ] int [ frac ] [ exp ]`, `exp = ("e" / "E") [ minus
/// / plus ] 1*DIGIT`. The grammar's `exponentPart` is `seq(choice('e','E'),
/// seq(optional('-'), digits))` — no `+`. This is **not** an ABI problem; the
/// grammar loads and parses everything else. It is a spec gap in a crate last
/// published 2024-11-11, and still present on the upstream `master` `grammar.js`.
///
/// It is hit in practice: `JSON.stringify` emits `1e+21` for magnitudes at or
/// above 1e21, so any JSON written by JavaScript containing a large number lands
/// an `ERROR` node on that token.
///
/// This test asserts the bug is **still there**, so the day it is fixed upstream
/// this goes red and the fixture and `GRAMMAR-ABI.md` get the `+` forms back.
#[test]
fn json_exponent_plus_sign_is_still_broken() {
    let language: Language = tree_sitter_json::LANGUAGE.into();
    let mut parser = Parser::new();
    parser.set_language(&language).expect("json loads");

    let mut clean = |src: &str| {
        let tree = parser_parse(&mut parser, src);
        defects(tree.root_node(), src).is_empty()
    };

    for ok in ["[1e2]", "[1E2]", "[1e-2]", "[1E-2]", "[-2.5e-4]", "[1.5E3]"] {
        assert!(clean(ok), "expected `{ok}` to parse clean");
    }
    for broken in ["[1e+2]", "[1E+2]", "[1e+21]", "[1.5E+3]"] {
        assert!(
            !clean(broken),
            "`{broken}` now parses — tree-sitter-json fixed the `+` exponent. \
             Put the `+` forms back in fixtures/json.json, drop the `known_gaps` \
             entry, and delete this test."
        );
    }
}

/// Characterisation of the reader boundary: which Steel-flavoured tokens the
/// Scheme grammar accepts and which it does not. Both directions are asserted so
/// that a change upstream — in either direction — shows up as a failing test
/// rather than as a silent behaviour shift in the highlighter.
#[test]
fn steel_reader_boundary_is_characterised() {
    let language: Language = tree_sitter_scheme::LANGUAGE.into();
    let mut parser = Parser::new();
    parser.set_language(&language).expect("scheme loads");

    // (source, must_parse_clean, why it is in the list)
    let probes: &[(&str, bool, &str)] = &[
        ("(define (f x) (+ x 1))", true, "define + application"),
        ("(lambda (x . rest) rest)", true, "improper lambda list"),
        ("(require \"steel/lists\")", true, "require"),
        ("(require-builtin steel/time)", true, "require-builtin"),
        (
            "`(a ,b ,@cs)",
            true,
            "quasiquote / unquote / unquote-splicing",
        ),
        (
            "#\\a #\\space #\\newline #\\tab #\\escape #\\x41",
            true,
            "char literals",
        ),
        ("\"esc \\\" \\\\ \\t \\x41;\"", true, "string escapes"),
        ("(f #:count 3 #:register #\\a)", true, "keyword arguments"),
        (
            "(let ([a 1] [b 2]) (+ a b))",
            true,
            "square-bracket bindings",
        ),
        (
            "(struct Point (x y) #:transparent)",
            true,
            "struct + struct option",
        ),
        (
            "(define-syntax m (syntax-rules () [(_ a) a]))",
            true,
            "syntax-rules",
        ),
        ("'#(1 2 3)", true, "vector"),
        ("#vu8(0 255)", true, "R6RS bytevector"),
        (
            "(when #true (void)) (if #false 1 2)",
            true,
            "`#true` / `#false` long booleans",
        ),
        (
            "(define/contract (f x) (->/c int? int?) x)",
            true,
            "contract form",
        ),
        (
            "(displayln (list->string (list #\\a #\\b)))",
            true,
            "char list → string",
        ),
        // Known gap 1: R7RS spells bytevectors `#u8(...)`; this grammar only has
        // the R6RS `#vu8(...)`. Steel writes bytes with `(bytes ...)`, so no
        // `runtime/*.scm` form is affected — recorded, not worked around.
        ("#u8(0 255)", false, "R7RS bytevector `#u8(` — known gap"),
        (
            "#| block |# #;(datum) ; line",
            true,
            "all three comment forms",
        ),
        ("(list 1/2 #xff #b1010 1e3 -2.5)", true, "numeric tower"),
        (
            "(~> xs (map f) (filter g))",
            true,
            "threading macro symbols",
        ),
        ("(hash 'a 1 'b 2)", true, "quoted symbols"),
        ("#'(syntax form)", true, "syntax quote"),
        // Known gap 2. `#` cannot appear in a bare symbol in this grammar
        // (`grammar.js`: `symbol_element` excludes `#`), so Steel's internal
        // `#%`-prefixed identifiers do not lex as symbols. They are compiler
        // internals and must never appear in `runtime/*.scm`; if one ever does,
        // the highlighter degrades for that form only.
        (
            "(#%plain-lambda (x) x)",
            false,
            "Steel `#%` internals — known gap",
        ),
    ];

    let mut wrong = Vec::new();
    for (src, expect_clean, why) in probes {
        let tree = parser.parse(src, None).expect("parser returns a tree");
        let found = defects(tree.root_node(), src);
        let clean = found.is_empty();
        if clean != *expect_clean {
            wrong.push(format!(
                "  {why}: expected {}, got {} for {src:?}{}",
                if *expect_clean { "clean" } else { "ERROR" },
                if clean { "clean" } else { "ERROR" },
                if found.is_empty() {
                    String::new()
                } else {
                    format!(" [{}]", found.join("; "))
                }
            ));
        }
    }
    assert!(
        wrong.is_empty(),
        "the Scheme grammar's reader boundary moved:\n{}",
        wrong.join("\n")
    );
}
