//! The view-tree constructors, **generated from the protocol** (`T080`, `T025`).
//!
//! Q12 gives Steel one job — *decide which pixels* — and one language to say it
//! in: `phosphor_core::view`. This module installs that language into the VM as
//! one procedure per node kind, named `view/<tag>`:
//!
//! ```scheme
//! (view/line (list (view/mode-chip "NORMAL" 'claude)
//!                  (view/spring)
//!                  (view/counter 'unseen 6 "unseen" 'meta)))
//! ```
//!
//! # Why generated rather than written
//!
//! `phosphor_core::view` says it outright, about a hand-written list of node
//! kinds *in a `.scm` file*: it *"would rot, and this cannot"*. The same
//! argument applies to a hand-written list on this side, so there is not one.
//! [`constructors`] walks `<Node as Wire>::TYPE` — the declared union — and
//! takes the tag, the field names and the field order from it. A node kind added
//! at `T078`'s table is callable from scheme with no edit here and no edit in
//! `runtime/`.
//!
//! The same walk is why an argument is checked rather than trusted: each
//! constructor decodes what it built back into its own type before answering, so
//! a misspelled tone is a Steel error naming the field, at the form that wrote
//! it, instead of a whole composition that fails to decode three layers up.
//!
//! # Records are hashes, and a few of them get sugar
//!
//! A record has no tag and therefore no name in the type language
//! ([`ParamType::Record`] is anonymous), so it cannot be enumerated the way the
//! node kinds can. The ones a composition actually writes — a styled run, a span
//! row, a split slot, a key hint, a float and its header — are listed in
//! [`RECORDS`] by name, and their *fields* still come from the schema. A name
//! that goes stale is a compile error here; a field that moves is picked up
//! silently. Anything not on that list is still writable as a plain
//! `(hash "field" …)`, which is what a record is on the wire.
//!
//! # The escape hatch is one of these and nothing more
//!
//! `view/spans` is `T080`'s hatch — the only constructor that takes styled rows,
//! because [`Node::Spans`] is the only node kind that carries them
//! (`scripts/lint-one-escape-hatch.sh`). It is generated by the same loop as
//! every other kind, which is the point: the hatch is a node kind, not a
//! privileged path.
//!
//! Owned by `spine`.

use std::sync::Arc;

use phosphor_core::registry::{Param, ParamType};
use phosphor_core::value::{Args, Value, Wire, WireError};
use phosphor_core::view::{
    Float, FloatHeader, KeyHint, Node, PickerColumn, Run, Slot, SpanRow, Tab, Tree,
};
use steel::rerrs::ErrorKind;
use steel::steel_vm::engine::Engine;
use steel::{SteelErr, SteelVal};

use crate::convert::{from_steel, to_steel};

/// Every constructor is named `view/<tag>`.
///
/// Namespaced for the same reason `phosphor/boot-files` is: these are names Rust
/// puts into the VM, and a bare `line` would be one `(define line …)` away from
/// silently becoming the protocol.
pub const PREFIX: &str = "view/";

/// A record type that gets a constructor of its own, and the shape to check it
/// against.
///
/// See the module docs: records are anonymous in the type language, so *which*
/// ones get sugar is a list, while *what fields they have* is not.
#[derive(Debug)]
pub struct RecordShape {
    /// The scheme name, without [`PREFIX`].
    pub name: &'static str,
    /// The declared shape — a [`ParamType::Record`], checked by the tests.
    pub ty: ParamType,
    /// Decodes the built value back into its own type.
    pub check: fn(&Value) -> Result<(), WireError>,
}

/// One entry per [`RecordShape`], and one line each: a name, its type, its
/// decoder.
macro_rules! records {
    ( $( $name:literal => $ty:ty ),* $(,)? ) => {
        &[ $( RecordShape {
            name: $name,
            ty: <$ty as Wire>::TYPE,
            check: |value| <$ty as Wire>::from_value(value).map(|_| ()),
        } ),* ]
    };
}

/// The records a composition writes by hand often enough to deserve a name.
///
/// `Child` is deliberately absent: it is the recursion, and a node already *is*
/// one (`view.rs`: *"the one place the declared type language says `any`"*), so
/// scheme passes a node wherever a child is wanted.
pub static RECORDS: &[RecordShape] = records! {
    "run" => Run,
    "span-row" => SpanRow,
    "slot" => Slot,
    "key-hint" => KeyHint,
    "picker-column" => PickerColumn,
    "tab" => Tab,
    "float-header" => FloatHeader,
    "float" => Float,
    "tree" => Tree,
};

/// One scheme procedure that builds one piece of a view tree.
#[derive(Clone)]
pub struct Constructor {
    /// The scheme name, `view/` included.
    pub name: String,
    /// The wire tag for a node kind; [`None`] for a record, which has none.
    pub tag: Option<&'static str>,
    /// Its arguments, in declared order — the positional order in scheme.
    pub params: &'static [Param],
    /// Decodes what was built, so a bad argument is caught where it was written.
    check: fn(&Value) -> Result<(), WireError>,
}

impl core::fmt::Debug for Constructor {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("Constructor")
            .field("name", &self.name)
            .field("tag", &self.tag)
            .field("arity", &self.params.len())
            .finish_non_exhaustive()
    }
}

/// Every constructor: one per node kind, then one per [`RECORDS`] entry.
///
/// # Panics
///
/// If [`Node`]'s declared shape stops being a union, or a [`RECORDS`] entry
/// stops being a record. Both are `const` facts about this crate's own
/// dependency, checked by the tests below and unreachable at runtime.
#[must_use]
pub fn constructors() -> Vec<Constructor> {
    let ParamType::Union(variants) = <Node as Wire>::TYPE else {
        panic!("a node's declared shape is a tagged union (view.rs)");
    };

    let mut out: Vec<Constructor> = variants
        .iter()
        .map(|variant| Constructor {
            name: format!("{PREFIX}{}", variant.tag),
            tag: Some(variant.tag),
            params: variant.fields,
            check: |value| Node::from_value(value).map(|_| ()),
        })
        .collect();

    for record in RECORDS {
        let ParamType::Record(params) = record.ty else {
            panic!("`{}` is declared as a record", record.name);
        };
        out.push(Constructor {
            name: format!("{PREFIX}{}", record.name),
            tag: None,
            params,
            check: record.check,
        });
    }

    out
}

/// Installs every constructor into `engine`, and answers how many.
///
/// Called once per VM, beside [`crate::registry::install`]: the vocabulary is
/// what Steel may *do*, and this is what Steel may *say*.
pub fn install(engine: &mut Engine) -> usize {
    let all = constructors();
    for constructor in &all {
        let name = constructor.name.clone();
        engine.register_value(&name, native(constructor.clone()));
    }
    all.len()
}

/// One constructor as a scheme procedure.
fn native(constructor: Constructor) -> SteelVal {
    SteelVal::anonymous_boxed_function(Arc::new(move |args: &[SteelVal]| build(&constructor, args)))
}

/// Positional scheme arguments to one piece of a tree.
fn build(constructor: &Constructor, args: &[SteelVal]) -> Result<SteelVal, SteelErr> {
    let Constructor {
        name, tag, params, ..
    } = constructor;

    if args.len() != params.len() {
        let wanted = params
            .iter()
            .map(|param| param.name)
            .collect::<Vec<_>>()
            .join(" ");
        return Err(SteelErr::new(
            ErrorKind::ArityMismatch,
            format!(
                "{name} takes {} argument(s) — ({name} {wanted})",
                params.len()
            ),
        ));
    }

    let mut fields = Args::new();
    for (param, arg) in params.iter().zip(args) {
        let value = from_steel(arg).map_err(|error| {
            SteelErr::new(
                ErrorKind::TypeMismatch,
                format!("{name}: argument `{}` — {error}", param.name),
            )
        })?;
        fields.set(param.name, value);
    }

    let built = match tag {
        Some(tag) => Value::tagged(tag, fields),
        None => Value::Record(fields),
    };
    (constructor.check)(&built)
        .map_err(|error| SteelErr::new(ErrorKind::TypeMismatch, format!("{name}: {error}")))?;
    Ok(to_steel(&built))
}

/// The node a composition answered, decoded.
///
/// The seam every composed surface comes back through — `T025`'s statusline and
/// anything else a `.scm` file returns. Errors carry the wire's own message,
/// which names the field.
///
/// # Errors
///
/// [`WireError`] when the value is not a node — the case a redefinition at the
/// REPL produces, and the reason a failed composition keeps the last good frame
/// rather than blanking it.
pub fn node(value: &SteelVal) -> Result<Node, ViewError> {
    let wire = from_steel(value).map_err(|error| ViewError::Uncrossable(error.to_string()))?;
    Node::from_value(&wire).map_err(ViewError::NotANode)
}

/// Why a value a composition answered is not a view tree.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ViewError {
    /// It held something the wire model has no case for — a closure, a port.
    Uncrossable(String),
    /// It crossed, and is not a node.
    NotANode(WireError),
}

impl core::fmt::Display for ViewError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Uncrossable(why) => write!(f, "{why}"),
            Self::NotANode(error) => write!(f, "not a view tree — {error}"),
        }
    }
}

impl std::error::Error for ViewError {}

#[cfg(test)]
mod tests {
    use super::*;
    use phosphor_core::view::Tone;

    fn engine() -> Engine {
        let mut engine = Engine::new();
        install(&mut engine);
        engine
    }

    fn run(engine: &mut Engine, source: &str) -> SteelVal {
        engine
            .compile_and_run_raw_program(source.to_owned())
            .unwrap_or_else(|error| panic!("{source} — {error}"))
            .last()
            .cloned()
            .expect("a form answers a value")
    }

    #[test]
    fn every_node_kind_has_a_constructor_and_the_list_cannot_rot() {
        let names: Vec<String> = constructors()
            .into_iter()
            .filter(|constructor| constructor.tag.is_some())
            .map(|constructor| constructor.name)
            .collect();
        let expected: Vec<String> = Node::TAGS
            .iter()
            .map(|tag| format!("{PREFIX}{tag}"))
            .collect();
        assert_eq!(names, expected);
    }

    #[test]
    fn every_named_record_is_declared_as_a_record() {
        for record in RECORDS {
            assert!(
                matches!(record.ty, ParamType::Record(_)),
                "`{}` is not a record",
                record.name
            );
        }
    }

    #[test]
    fn install_binds_every_constructor_to_a_procedure() {
        let mut engine = Engine::new();
        let installed = install(&mut engine);
        assert_eq!(installed, constructors().len());
        for constructor in constructors() {
            let value = engine
                .extract_value(&constructor.name)
                .unwrap_or_else(|_| panic!("`{}` is not bound", constructor.name));
            assert!(
                matches!(value, SteelVal::BoxedFunction(_)),
                "`{}` is bound to something that is not callable",
                constructor.name
            );
        }
    }

    #[test]
    fn a_composed_node_decodes_into_the_kind_it_names() {
        let mut engine = engine();
        let value = run(
            &mut engine,
            "(view/line (list (view/mode-chip \"NORMAL\" 'claude) (view/spring)))",
        );
        let Node::Line { children } = node(&value).expect("a line") else {
            panic!("the composition said `line`");
        };
        assert_eq!(children.len(), 2);
        let Node::ModeChip { label, tone } = children[0].node() else {
            panic!("the chip is first");
        };
        assert_eq!(label, "NORMAL");
        assert_eq!(*tone, Tone::Claude);
    }

    #[test]
    fn the_spans_hatch_is_reachable_from_scheme_and_nothing_else_is_needed() {
        // `T080`: a surface the primitive set does not cover, drawn out of rows
        // of styled runs and no other node kind.
        let mut engine = engine();
        let value = run(
            &mut engine,
            r#"(view/spans
                 (list (view/span-row (list (view/run "store" 'steel 'plain)) 'selection)
                       (view/span-row (list (view/run "  regions" 'meta 'plain)) void)))"#,
        );
        let Node::Spans { rows } = node(&value).expect("a spans node") else {
            panic!("the hatch composes a `spans` node");
        };
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].runs[0].text, "store");
        assert_eq!(rows[0].runs[0].tone, Tone::Steel);
        assert!(rows[1].tint.is_none(), "an absent tint is the ground");
    }

    #[test]
    fn an_optional_field_takes_void_and_a_symbol_takes_a_choice() {
        let mut engine = engine();
        let value = run(&mut engine, "(view/counter 'unseen 6 void 'meta)");
        let Node::Counter { label, count, .. } = node(&value).expect("a counter") else {
            panic!("a counter");
        };
        assert_eq!(count, 6);
        assert_eq!(label, None, "no word is `●6`, not an empty word");
    }

    #[test]
    fn the_wrong_number_of_arguments_names_the_fields_it_wanted() {
        let mut engine = engine();
        let error = engine
            .compile_and_run_raw_program("(view/mode-chip \"NORMAL\")".to_owned())
            .expect_err("the chip takes a label and a tone");
        assert_eq!(error.kind(), ErrorKind::ArityMismatch);
        assert!(error.to_string().contains("tone"), "{error}");
    }

    #[test]
    fn a_tone_the_palette_does_not_name_is_caught_at_the_form_that_wrote_it() {
        // The whole reason a constructor checks rather than trusts: this is
        // three layers down in a real composition, and the error still says
        // `mode-chip` and `tone`.
        let mut engine = engine();
        let error = engine
            .compile_and_run_raw_program("(view/mode-chip \"NORMAL\" 'chartreuse)".to_owned())
            .expect_err("`chartreuse` is not an actor");
        assert_eq!(error.kind(), ErrorKind::TypeMismatch);
        let message = error.to_string();
        assert!(message.contains("view/mode-chip"), "{message}");
        assert!(message.contains("tone"), "{message}");
    }

    #[test]
    fn a_value_that_is_not_a_node_is_reported_rather_than_drawn() {
        let mut engine = engine();
        let value = run(&mut engine, "(hash \"kind\" \"buffer-view\")");
        let error = node(&value).expect_err("`buffer-view` is not a node kind");
        assert!(matches!(error, ViewError::NotANode(_)), "{error:?}");
        assert!(error.to_string().contains("buffer-view"), "{error}");
    }

    #[test]
    fn a_closure_cannot_be_smuggled_into_a_tree() {
        let mut engine = engine();
        let error = engine
            .compile_and_run_raw_program("(view/label (lambda () 1) 'text 'plain)".to_owned())
            .expect_err("a tree is plain data");
        assert_eq!(error.kind(), ErrorKind::TypeMismatch);
    }

    #[test]
    fn a_record_constructor_takes_the_fields_the_schema_declares() {
        let mut engine = engine();
        let value = run(
            &mut engine,
            "(view/slot (hash \"kind\" \"cells\" \"cells\" 1) (view/divider))",
        );
        let wire = from_steel(&value).expect("a slot crosses");
        let slot = Slot::from_value(&wire).expect("a slot decodes");
        assert!(matches!(slot.child.node(), Node::Divider {}));
    }
}
